routes/web.php
<?php
use Illuminate\Database\Eloquent\Model;
use App\Artikel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();
//======Route untuk Front-End
Route::get('/home', 'HomeController@index')->name('home');

//======Beranda Front-End
// Route::get('/', 'BerandaController@index')->name('beranda');
Route::get('/', 'BerandaController@index')->name('beranda');

//======Kategori Front-End
Route::get('/kategori', function () {
    return view('frontend.pages.kategori');
});
//=====Akhir Route untuk Front-End

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

//=====Route untuk admin (Backend)

Route::get('/admin', 'AdminController@index')->name('admin.index');
// Route::get('/admin/post')

//======dashboard
// Route::get('/', 'DashboardController@index')->name('dashboard');

//======categori
// Route::get('/categori', 'CategoriController@index')->name('categori');

// //======cart
// Route::get('/cart', 'CartController@index')->name('cart');

// //product_list
// Route::get('/product_list', 'Product_listController@index')->name('product_list');

//=====Akhir Route untuk Front-End

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

//=====Route untuk admin (Backend)

Route::get('/admin', 'AdminController@index')->name('admin.index');

// Untuk Post di Blog
Route::resource('artikel', 'ArtikelController');

// Produk dan Kategori
Route::get('/admin/produk/kategori', 'KategoriController@index')->name('produk_kategori');
Route::get('/admin/produk/kategori/tambah', 'KategoriController@create')->name('tambah_produk_kategori');
Route::post('/admin/produk/kategori', 'KategoriController@save');
Route::get('/admin/produk/kategori/{id}/edit', 'KategoriController@edit')->name('ubah_produk_kategori');
Route::put('/admin/produk/kategori/{id}', 'KategoriController@update')->name('update_produk_kategori');
Route::get('/admin/produk/kategori/{id}', 'KategoriController@show')->name('view_produk_kategori');
Route::delete('/admin/produk/kategori/{id}', 'KategoriController@destroy')->name('hapus_produk_kategori');

Route::get('/admin/produk', 'ProdukController@index')->name('produk');
Route::get('/admin/produk/tambah', 'ProdukController@create')->name('tambah_produk');
Route::post('/admin/produk', 'ProdukController@save');
Route::get('/admin/produk/{id}', 'ProdukController@show')->name('view-produk');
Route::get('/admin/produk/{id}/edit', 'ProdukController@edit')->name('ubah-produk');
Route::put('/admin/produk/{id}', 'ProdukController@update')->name('update-produk');
Route::delete('/admin/produk/{id}', 'ProdukController@destroy')->name('hapus-produk');
// Route::get('/testdb', function(){            //Saya gunakan untuk mengetes kondisi tabel
//     $test = DB::table('artikel') -> get();
//     dd($test);
// });

// Route::get('/show', function () {           //Saya gunakan untuk tes halaman
//     return view('backend.pages.articles.show');
// });

//====Akhir Route untuk admin


//====Route untuk Toko
// Route::get('/', 'TokoController@index');
Route::get('/blog', 'TokoController@blog');
Route::get('/blog/show', 'TokoController@blogshow')->name('blog.show');

Route::get('/show', function () {
    return view('backend.pages.articles.show');
});

Route::post('/atc', 'CartController@add')->name('atc');

//====Akhir Route untuk admin
//====Akhir Route untuk Toko

//====Akhir Route untuk admin

//====Akhir Route untuk Toko

resources/views/backend/pages/articles/create.blade.php
@extends('backend.layouts.adminmaster')

@section('content')
<div class="box box-primary ml-3 mr-4">
            <div class="box-header with-border">
              <h3 class="box-title">Form Artikel</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{ route('artikel.store') }}" method="POST">
            @csrf
              <div class="box-body">
                <div class="form-group">
                  <label for="judul">Judul Artikel</label>
                  <input type="text" class="form-control" id="judulartikel" placeholder="Masukan judul" name="judulartikel">
                </div>
                <div class="form-group">
                  <label>Isi</label>
                  <textarea class="form-control" rows="3" placeholder="Enter ..." name="isiartikel"></textarea>
                </div>
                <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile" name="imageartikel">

                  <p class="help-block">Example block-level help text here.</p>
                </div>
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Check me out
                  </label>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>

 @endsection

resources/views/backend/pages/articles/edit.blade.php
@extends('backend.layouts.adminmaster')

@section('content')
<div class="box box-primary ml-3 mr-4">
            <div class="box-header with-border">
              <h3 class="box-title">Edit Artikel {{$artikel->id}}</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="/artikel/{{$artikel->id}}" method="POST">
            @csrf
            @method('PUT')
              <div class="box-body">
                <div class="form-group">
                  <label for="judul">Judul Artikel</label>
                  <input type="text" class="form-control" id="judulartikel" placeholder="Masukan judul" name="judulartikel" value="{{$artikel->judul}}">
                </div>
                <div class="form-group">
                  <label>Isi</label>
                  <textarea class="form-control" rows="3" placeholder="Enter ..." name="isiartikel" >{{$artikel->isi}}</textarea>
                </div>
                <div class="form-group">
                  <label for="exampleInputFile">File input</label>
                  <input type="file" id="exampleInputFile" name="imageartikel" value="{{$artikel->thumbnail}}">

                  <p class="help-block">Example block-level help text here.</p>
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Edit</button>
              </div>
            </form>
          </div>

 @endsection

resources/views/backend/pages/articles/post.blade.php
@extends('backend.layouts.adminmaster')

@section('content')
<div class="container-fluid">
 <div class="d-sm-flex align-items-center justify-content-between mb-4">
 <h1 class="h3 mb-0 text-gray-800">Post Management</h1>
 <a href="{{ route('artikel.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-bullhorn fa-sm text-white-50"></i> Create Post</a>
 </div>
 <div class="card shadow mb-4">
     <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary">Data artikel</h6>
     </div>
     <div class="card-body">
         <div class="table-responsive">
             <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
              <div class="row">
               <div class="col-sm-12 col-md-6">
                <div class="dataTables_length" id="dataTable_length">
                 <label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
                  <option value="10">10</option>
                  <option value="25">25</option>
                  <option value="50">50</option>
                  <option value="100">100</option></select> 
                  entries</label>
                 </div>
                </div>
               <div class="col-sm-12 col-md-6">
                <div id="dataTable_filter" class="dataTables_filter">
                 <label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label>
                </div></div>
               </div>
               <div class="row">
                <div class="col-sm-12">
                 <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                 <thead>
                     <tr role="row">
                      <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 149px;">Judul</th>
                      <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 247px;">Isi</th>
                      <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 100px;">Thumbnails</th>
                      <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 90px;">Menu</th>
                     </tr>
                 </thead>
                 <tfoot>
                     <tr>
                      <th rowspan="1" colspan="1">Judul</th>
                      <th rowspan="1" colspan="1">Isi</th>
                      <th rowspan="1" colspan="1">Thumbnails</th>
                      <th rowspan="1" colspan="1">Menu</th>
                     </tr>
                 </tfoot>
                 <tbody>
                 @forelse ($artikel as $key=>$artikel)
                    <tr role="row" class="odd">
                        <!-- <td>{{$key + 1}}</th> -->
                        <td>{{$artikel->judul}}</td>
                        <td>{{$artikel->isi}}</td>
                        <td>{{$artikel->thumbnail}}</td>
                        <td>
                            <a href="/artikel/{{$artikel->id}}" class="btn btn-info">Show</a>
                            <a href="/artikel/{{$artikel->id}}/edit" class="btn btn-primary">Edit</a>
                            <form action="/artikel/{{$artikel->id}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" class="btn btn-danger my-1 d-inline" value="Delete">
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr colspan="3">
                        <td>No data</td>
                    </tr>  
                @endforelse    
                    </tbody>
             </table>
            </div>
           </div>
           <div class="row">
            <div class="col-sm-12 col-md-5">
             <div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries
             </div>
            </div>
            <div class="col-sm-12 col-md-7">
             <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
              <ul class="pagination">
               <li class="paginate_button page-item previous disabled" id="dataTable_previous"><a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
              </li>
              <li class="paginate_button page-item active"><a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a>
             </li>
             <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a>
            </li>
             <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a>
            </li>
            <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a>
           </li>
           <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a>
          </li>
          <li class="paginate_button page-item "><a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a>
         </li>
         <li class="paginate_button page-item next" id="dataTable_next"><a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
        </li>
       </ul>
      </div>
     </div>
    </div>
   </div>
         </div>
     </div>
 </div>
</div>



@endsection

resources/views/backend/pages/articles/show.blade.php
@extends('backend.layouts.adminmaster')

@section('content')
<div class="card shadow mb-4">
 <div class="card-header py-3">
     <h6 class="m-0 font-weight-bold text-primary">{{$artikel->judul}}</h6>
 </div>
 <div class="card-body">
     {{$artikel->isi}}
 </div>
</div>


@endsection